language: node_js
node_js:
  - 8

branches:
  only:
    - master

#build:
#  ci:
#    - npm i
#    - npm run test:unit
#
#  cache: true
#  chache_dir_list:
#    - $SHIPPABLE_BUILD_DIR/node_modules

jobs:
  - name: install_dependencies
    type: runSh
    steps:
      - IN: app_gitRepo
      - TASK:
        - script: npm i
      - OUT: dependencies
        replicate: app_gitRepo

  - name: run_tests
      type: runSh
      steps:
        - IN: app_gitRepo
        - TASK:
          - script: npm run test:unit
